### ISSUE TITLE
IronCore Service

### ISSUE THREAD

**Issue by stevennt** [IronCoreLabs/ironhide#45]
Is that IronCore service an open source project? Ironhide seems to rely much on that IronCore service.

**Comment by clintfred** [comment]
Thanks for you question. The service is not open source at this time. Depending on your use-case, we do offer licenses for the service if that's something you are interested in. 

The service provides key management as well as transform key computation. The service never sees plaintext data or a user's private key. If you have more questions, please feel free to ask them here.
