### ISSUE TITLE
这个错误是什么意思

### ISSUE THREAD

**Issue by yanxiansheng123** [IronCoreLabs/ironhide#54]
![image](https://user-images.githubusercontent.com/66814668/161528595-29222062-3319-4706-9a60-798c233e22a3.png)

**Comment by skeet70** [comment]
Try to remove and reinstall `ironhide` (`npm uninstall -g @ironcorelabs/ironhide; npm install -g @ironcorelabs/ironhide`) and keep an eye out for any errors during installation.

`Cannot find module './bin-package/index.node` indicates to me that the installation of the `ironnode` dependency failed. That probably means you're running an unsupported combination of node version and platform, or something else went wrong during the installation. Either way re-running the install should give a more useful error. If it doesn't, some more information may be helpful (which version of `ironhide` you're installing, what platform you're on, what version of npm/node you're running, etc).

**Comment by yanxiansheng123** [comment]
![image](https://user-images.githubusercontent.com/66814668/161586149-88ce0774-4532-404c-904f-f698861ef27c.png)

**Comment by skeet70** [comment]
![image](https://user-images.githubusercontent.com/1424117/161590250-da5c0842-cde3-4b66-94b6-b2b30fd5a228.png)

This was on a fresh Kali image with the latest release. All your versions seem correct, but the missing `index.node` still indicates that the binary for `@ironcorelabs/recrypt-node-binding` didn't get installed. There were no error messages when you uninstalled/reinstalled `ironhide`? What's the result of `ls /usr/local/lib/node_modules/@ironcorelabs/ironhide/node_modules/@ironcorelabs/recrypt-node-binding/` for you? 

Do you maybe have post-install scripts turned off as a security feature in your node configuration, or did you install with the `--ignore-scripts` flag? Either of those would result in the binary not being pulled down for the dependency. If you either can't or are unwilling to disable that flag for this install (or it still doesn't work for some reason), you can manually install `bin-package/index.node` by [downloading the binary yourself](https://github.com/IronCoreLabs/recrypt-node-binding/releases/download/0.8.2/index-v0.8.2-node-v93-linux-x64-glibc.tar.gz) and extracting it to the location that the error is indicating. If you're not willing to install a pre-built binary at all, `recrypt-node-binding` is open source and you can follow the [local development instructions](https://github.com/IronCoreLabs/recrypt-node-binding#local-development) to build it yourself from source, and copy the resulting `index.node` file to the location that your current error indicates.

Hopefully that helps, let us know if you're able to get it going one of those ways!

**Comment by yanxiansheng123** [comment]
![image](https://user-images.githubusercontent.com/66814668/161667812-d075d34d-b73b-45ff-8472-2ff4d464492d.png)
多谢您一直的回答 ，我安装的时候它报了这个警告

**Comment by yanxiansheng123** [comment]
我找到了办法 我把node和npm降级了 然后就可以了 谢谢您的回答

**Comment by skeet70** [comment]
I'm glad it worked for you! Still not sure why it failed an all, I couldn't reproduce on the same node and npm version. I'll close for now though and consider it environmental.
